$('.promo__slider').slick({
  dots: true,
  arrows: true,
  infinite: true,
  autoplay: false,
  pauseOnHover: false,
  pauseOnFocus: false,
  autoplaySpeed: 3000,
  variableWidth: false,
  speed: 500,
  fade: true,
  adaptiveHeight: false,
  vertical: false,
  verticalSwiping: false,
  // slidesPerRow: 0,
  slidesToShow: 1,
  slidesToScroll: 1,
  appendDots: $('.promo__dots .container'),
  prevArrow: $('.promo__arrows .arrows__arrow-prev'),
  nextArrow: $('.promo__arrows .arrows__arrow-next')
});
